# -*- coding: utf-8 -*-
"""edupredict_search.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-eF95uI47JFF__JHlWAeyl55qA6JRXaw

# **EduPredict**: Student Academic Performance Forecasting System
"""

import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
from sklearn.ensemble import RandomForestClassifier
from xgboost import XGBClassifier
import matplotlib.pyplot as plt
import seaborn as sns

# ========== 1. LOAD DATA ==========
# Load both datasets (Math and Portuguese)
math_df = pd.read_csv('student-mat.csv', sep=';')
por_df = pd.read_csv('student-por.csv', sep=';')

# Combine them (or use one - we'll use Portuguese as it has more samples)
df = por_df.copy()

# ========== 2. CREATE TARGET ==========
# Create binary target: Pass (1) if G3 >= 10, else Fail (0)
df['Pass'] = (df['G3'] >= 10).astype(int)

print(f"Dataset shape: {df.shape}")
print(f"Pass: {df['Pass'].sum()}, Fail: {len(df) - df['Pass'].sum()}")
print(f"Pass rate: {df['Pass'].mean():.2%}")

# ========== 3. ENCODE CATEGORICAL VARIABLES ==========
# Identify categorical columns
categorical_cols = df.select_dtypes(include=['object']).columns.tolist()
print(f"Categorical columns: {categorical_cols}")

# Label encode all categorical columns
label_encoders = {}
for col in categorical_cols:
    le = LabelEncoder()
    df[col] = le.fit_transform(df[col].astype(str))
    label_encoders[col] = le

# Remove target and non-predictive columns
X = df.drop(['Pass', 'G1', 'G2', 'G3'], axis=1)  # Remove intermediate grades
y = df['Pass']

print(f"Features: {X.shape[1]}")
print(f"Feature names: {X.columns.tolist()}")

""" ## Data Partitioning and Initial Baseline Model Evaluation"""

# ========== 4. TRAIN/TEST SPLIT ==========
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42, stratify=y)

print(f"Training: {X_train.shape[0]} samples")
print(f"Testing: {X_test.shape[0]} samples")

# ========== 5. BASELINE: RANDOM FOREST (ALL FEATURES) ==========
print("\n" + "="*50)
print("BASELINE: Random Forest with ALL features")
print("="*50)

rf_baseline = RandomForestClassifier(n_estimators=100, random_state=42)
rf_baseline.fit(X_train, y_train)
y_pred_baseline = rf_baseline.predict(X_test)

baseline_accuracy = accuracy_score(y_test, y_pred_baseline)
print(f"Baseline Accuracy: {baseline_accuracy:.2%}")
print(f"Features used: {X.shape[1]}")

# Feature importance (this tells us which features matter most)
feature_importance = pd.DataFrame({
    'feature': X.columns,
    'importance': rf_baseline.feature_importances_
}).sort_values('importance', ascending=False)

print("\nTop 10 Features (Baseline):")
print(feature_importance.head(10))

"""## Implementation and Execution of the Binary Snake Optimizer (BSO)"""

# ========== 6. BINARY SNAKE OPTIMIZER FOR FEATURE SELECTION ==========
class BinarySnakeOptimizer:
    """
    Simplified Binary Snake Optimizer for Feature Selection
    Based on: Modified Binary Snake Optimizer (MBSO) for feature selection
    """
    def __init__(self, n_population=20, n_iterations=30, threshold=0.5):
        self.n_population = n_population
        self.n_iterations = n_iterations
        self.threshold = threshold
        self.best_fitness = -float('inf')
        self.best_position = None
        self.fitness_history = []

    def fit(self, X_train, y_train, X_test, y_test, model):
        n_features = X_train.shape[1]

        # Initialize population (binary positions)
        population = np.random.randint(0, 2, size=(self.n_population, n_features))

        # Evaluate initial population
        fitness = np.array([self.evaluate_individual(ind, X_train, y_train, X_test, y_test, model)
                           for ind in population])

        # Find best
        best_idx = np.argmax(fitness)
        self.best_fitness = fitness[best_idx]
        self.best_position = population[best_idx].copy()

        print(f"Initial Best Fitness: {self.best_fitness:.4f}")

        # Main BSO loop
        for iteration in range(self.n_iterations):
            # Temperature decreases over time
            temp = 0.5 * (1 - iteration / self.n_iterations)

            # Update each snake
            for i in range(self.n_population):
                # Randomly choose exploration or exploitation
                if np.random.random() < temp:
                    # Exploration: flip random bits
                    for j in range(n_features):
                        if np.random.random() < 0.1:  # Mutation rate
                            population[i][j] = 1 - population[i][j]
                else:
                    # Exploitation: move toward best solution
                    for j in range(n_features):
                        if population[i][j] != self.best_position[j]:
                            if np.random.random() < 0.3:  # Crossover rate
                                population[i][j] = self.best_position[j]

                # Ensure binary (0/1)
                population[i] = np.where(population[i] > 0.5, 1, 0)

                # Evaluate new individual
                new_fitness = self.evaluate_individual(population[i], X_train, y_train, X_test, y_test, model)

                # Update if better
                if new_fitness > fitness[i]:
                    fitness[i] = new_fitness
                    if new_fitness > self.best_fitness:
                        self.best_fitness = new_fitness
                        self.best_position = population[i].copy()

            # Record progress
            self.fitness_history.append(self.best_fitness)

            if (iteration + 1) % 5 == 0:
                n_selected = int(self.best_position.sum())
                print(f"Iteration {iteration+1}/{self.n_iterations} | Best Fitness: {self.best_fitness:.4f} | Features: {n_selected}")

        return self

    def evaluate_individual(self, individual, X_train, y_train, X_test, y_test, model):
        """Evaluate a feature subset using the model"""
        # Select features where individual == 1
        selected_features = [i for i, val in enumerate(individual) if val == 1]

        # If no features selected, return poor fitness
        if len(selected_features) == 0:
            return 0.0

        # Train model on selected features
        X_train_selected = X_train.iloc[:, selected_features]
        X_test_selected = X_test.iloc[:, selected_features]

        try:
            model_clone = model.__class__(**model.get_params())
            model_clone.fit(X_train_selected, y_train)
            y_pred = model_clone.predict(X_test_selected)
            accuracy = accuracy_score(y_test, y_pred)

            # Fitness = accuracy - penalty for too many features
            n_features_used = len(selected_features)
            total_features = X_train.shape[1]

            # Balance accuracy and feature reduction
            fitness = accuracy * 0.7 + (1 - n_features_used/total_features) * 0.3
            return fitness
        except:
            return 0.0

    def get_selected_features(self):
        return [i for i, val in enumerate(self.best_position) if val == 1]

# ========== 7. RUN BSO FEATURE SELECTION ==========
print("\n" + "="*50)
print("FEATURE SELECTION with Binary Snake Optimizer")
print("="*50)

# Use Random Forest as the evaluator
rf_evaluator = RandomForestClassifier(n_estimators=50, random_state=42)

# Run BSO
bso = BinarySnakeOptimizer(n_population=15, n_iterations=20)
bso.fit(X_train, y_train, X_test, y_test, rf_evaluator)

# Get selected features
selected_indices = bso.get_selected_features()
selected_features = X.columns[selected_indices].tolist()

print(f"\nSelected {len(selected_features)} features:")
print(selected_features)

"""## Performance Evaluation and Visual Analysis of BSO-Optimized Models"""

# ========== 8. TRAIN WITH SELECTED FEATURES ==========
print("\n" + "="*50)
print("MODELS with BSO-SELECTED FEATURES")
print("="*50)

# Prepare selected feature data
X_train_selected = X_train.iloc[:, selected_indices]
X_test_selected = X_test.iloc[:, selected_indices]

# Random Forest
rf_selected = RandomForestClassifier(n_estimators=100, random_state=42)
rf_selected.fit(X_train_selected, y_train)
rf_pred = rf_selected.predict(X_test_selected)
rf_acc = accuracy_score(y_test, rf_pred)

print(f"\nRandom Forest with BSO features:")
print(f"  Accuracy: {rf_acc:.2%}")
print(f"  Features: {len(selected_indices)} (reduced from {X.shape[1]})")

# XGBoost
xgb_selected = XGBClassifier(n_estimators=100, random_state=42, use_label_encoder=False, eval_metric='logloss')
xgb_selected.fit(X_train_selected, y_train)
xgb_pred = xgb_selected.predict(X_test_selected)
xgb_acc = accuracy_score(y_test, xgb_pred)

print(f"\nXGBoost with BSO features:")
print(f"  Accuracy: {xgb_acc:.2%}")
print(f"  Features: {len(selected_indices)} (reduced from {X.shape[1]})")

# ========== 9. COMPARISON TABLE ==========
print("\n" + "="*50)
print("RESULTS SUMMARY")
print("="*50)

results_df = pd.DataFrame({
    'Model': ['Random Forest (All)', 'Random Forest (BSO)', 'XGBoost (BSO)'],
    'Accuracy': [baseline_accuracy, rf_acc, xgb_acc],
    'Features Used': [X.shape[1], len(selected_indices), len(selected_indices)]
})

print(results_df.to_string(index=False))

# ========== 10. VISUALIZE ==========
# Plot fitness progression
plt.figure(figsize=(10, 5))
plt.plot(bso.fitness_history, marker='o')
plt.title('BSO Fitness Progression (Feature Selection)')
plt.xlabel('Iteration')
plt.ylabel('Fitness Score')
plt.grid(True)
plt.show()

# Plot feature importance from best model
feature_imp_selected = pd.DataFrame({
    'feature': selected_features,
    'importance': rf_selected.feature_importances_
}).sort_values('importance', ascending=True)

plt.figure(figsize=(10, 6))
plt.barh(feature_imp_selected['feature'], feature_imp_selected['importance'])
plt.title(f'Top {len(selected_features)} Features Selected by BSO')
plt.xlabel('Importance')
plt.tight_layout()
plt.show()

"""## Confusion Matrix"""

# ========== 11. CONFUSION MATRIX ==========
from sklearn.metrics import confusion_matrix, ConfusionMatrixDisplay

# Compare baseline vs BSO
fig, axes = plt.subplots(1, 2, figsize=(12, 5))

# Baseline
cm_baseline = confusion_matrix(y_test, y_pred_baseline)
disp_baseline = ConfusionMatrixDisplay(cm_baseline, display_labels=['Fail', 'Pass'])
disp_baseline.plot(ax=axes[0])
axes[0].set_title(f'Baseline (All Features)\nAccuracy: {baseline_accuracy:.1%}')

# BSO
cm_bso = confusion_matrix(y_test, rf_pred)
disp_bso = ConfusionMatrixDisplay(cm_bso, display_labels=['Fail', 'Pass'])
disp_bso.plot(ax=axes[1])
axes[1].set_title(f'BSO Feature Selection\nAccuracy: {rf_acc:.1%}')

plt.tight_layout()
plt.show()

"""## Implementation of the Heuristic Intervention Agent"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, confusion_matrix, ConfusionMatrixDisplay

# =========================================================
# 1. FINAL MODEL TRAINING (Using BSO Selected Features)
# =========================================================
# 'selected_features' comes from your BSO get_selected_features()
X_train_selected = X_train[selected_features]
X_test_selected = X_test[selected_features]

# Train the Final "Brain" of the system
rf_model = RandomForestClassifier(n_estimators=100, max_depth=10, random_state=42)
rf_model.fit(X_train_selected, y_train)

# Final Prediction for Evaluation
y_pred = rf_model.predict(X_test_selected)
final_acc = accuracy_score(y_test, y_pred)

print(f"Final Model Accuracy (with BSO Features): {final_acc:.2%}")

# =========================================================
# 2. HEURISTIC INTERVENTION SEARCH AGENT
# =========================================================
def find_intervention_path(student_row, model, selected_features):
    """
    AI Agent that searches for the minimum behavioral changes
    to turn a predicted FAIL into a PASS.
    """
    # Current prediction
    current_pred = model.predict(student_row)[0]

    if current_pred == 1:
        return "✅ Student is already predicted to PASS. No intervention needed."

    # Define features that can be changed (Actionable)
    # These must be part of the features BSO selected to work
    actionable_mapping = {
        'studytime': {'action': 'increase', 'max': 4},
        'absences': {'action': 'decrease', 'min': 0},
        'failures': {'action': 'decrease', 'min': 0},
        'goout': {'action': 'decrease', 'min': 1},
        'Dalc': {'action': 'decrease', 'min': 1}
    }

    # Filter mapping to only include features BSO actually selected
    active_actions = [f for f in actionable_mapping.keys() if f in selected_features]

    modified_student = student_row.copy()
    steps = []

    # Heuristic Search Loop: Try to improve features one by one
    for feature in active_actions:
        action = actionable_mapping[feature]['action']

        # Try to improve the feature up to 3 times (iterations)
        for _ in range(3):
            if action == 'increase' and modified_student[feature].values[0] < actionable_mapping[feature]['max']:
                modified_student[feature] += 1
                steps.append(f"Increase {feature}")
            elif action == 'decrease' and modified_student[feature].values[0] > actionable_mapping[feature]['min']:
                # For absences, decrease by 5; for others by 1
                reduction = 5 if feature == 'absences' else 1
                modified_student[feature] = max(actionable_mapping[feature]['min'], modified_student[feature] - reduction)
                steps.append(f"Reduce {feature}")

            # Check if this change flipped the prediction to PASS
            if model.predict(modified_student)[0] == 1:
                return f"⚠️ INTERVENTION FOUND: To Pass, the student should: {' AND '.join(dict.fromkeys(steps))}"

    return "❌ CRITICAL: Basic behavioral changes are insufficient. Intensive academic counseling required."

# =========================================================
# 3. DEMONSTRATION: Testing the AI Agent
# =========================================================
print("\n" + "="*50)
print("AI AGENT: INTERVENTION CASE STUDY")
print("="*50)

# Find a student in the test set who is predicted to fail
fail_indices = np.where(y_pred == 0)[0]

if len(fail_indices) > 0:
    # Pick the first student who is failing
    idx = fail_indices[0]
    target_student = X_test_selected.iloc[[idx]]

    print(f"Target Student ID (Index): {X_test_selected.index[idx]}")
    print(f"Initial Prediction: FAIL")

    # Run Search
    result = find_intervention_path(target_student, rf_model, selected_features)
    print(f"AI Recommendation: {result}")
else:
    print("No failing students found in the test set to demonstrate intervention.")

# =========================================================
# 4. FINAL VISUALIZATION: CONFUSION MATRIX
# =========================================================
plt.figure(figsize=(6, 5))
cm = confusion_matrix(y_test, y_pred)
disp = ConfusionMatrixDisplay(confusion_matrix=cm, display_labels=['Fail', 'Pass'])
disp.plot(cmap='Blues', values_format='d')
plt.title(f"Final EduPredict Performance\n(BSO Features | Acc: {final_acc:.1%})")
plt.show()

"""#### While the model achieved an overall accuracy of 83.1%, the confusion matrix reveals a significant challenge: Class Imbalance. Because the majority of students in the dataset passed, the model became biased toward the 'Pass' class, resulting in 0 correct 'Fail' predictions. This highlights the Accuracy Paradox, where a high accuracy score does not necessarily mean the model is effective at catching at-risk students.##"""

# Add 'class_weight' to balance the 0
rf_model = RandomForestClassifier(n_estimators=100, class_weight='balanced', random_state=42)

"""####Why do this? class_weight='balanced' tells the AI that failing a "Fail" prediction is a much bigger mistake than failing a "Pass" prediction. This will likely lower your total accuracy to maybe 75%, but it will actually start catching the students who are failing, which is the whole point of your EduPredict system!"""

from sklearn.metrics import confusion_matrix, ConfusionMatrixDisplay, classification_report, accuracy_score
import matplotlib.pyplot as plt

# 1. Initialize and Train the Balanced Model
# 'class_weight=balanced' is the key to fixing the 0 result
rf_model_balanced = RandomForestClassifier(
    n_estimators=100,
    class_weight='balanced',
    random_state=42
)

# Fit using the features selected by your BSO
rf_model_balanced.fit(X_train_selected, y_train)

# 2. Make Predictions
y_pred_bal = rf_model_balanced.predict(X_test_selected)

# 3. Calculate New Accuracy
bal_acc = accuracy_score(y_test, y_pred_bal)

# 4. Print detailed performance report
# This will show the 'Recall' for the Fail class (how many we caught)
print("--- Detailed Performance Report ---")
print(classification_report(y_test, y_pred_bal, target_names=['Fail', 'Pass']))

# 5. Visualize the Result (The Confusion Matrix)
plt.figure(figsize=(8, 6))
cm = confusion_matrix(y_test, y_pred_bal)
disp = ConfusionMatrixDisplay(confusion_matrix=cm, display_labels=['Fail', 'Pass'])

# Using a different color (Greens) to distinguish this improved version
disp.plot(cmap='Greens', values_format='d')

plt.title(f"Improved EduPredict Performance\n(Balanced Class Weights | Accuracy: {bal_acc:.1%})")
plt.grid(False) # Clean look
plt.show()

# 6. Demonstration: Show that the AI Agent now works better
print("\n" + "="*50)
print("TESTING INTERVENTION AGENT ON BALANCED MODEL")
print("="*50)

# Run the intervention path finder using the new balanced model
fail_indices = np.where(y_pred_bal == 0)[0]
if len(fail_indices) > 0:
    target_student = X_test_selected.iloc[[fail_indices[0]]]
    print(f"Target Student ID: {X_test_selected.index[fail_indices[0]]}")
    print(f"Prediction: FAIL")
    # Using the function we defined earlier
    recommendation = find_intervention_path(target_student, rf_model_balanced, selected_features)
    print(f"AI Recommendation: {recommendation}")

"""#### In Phase 2, we noticed the model was biased due to class imbalance. We implemented 'Balanced Class Weights' to ensure the AI prioritizes catching at-risk students. While the overall accuracy decreased slightly, the Recall for the 'Fail' class improved significantly, making the system a much more effective tool for educational intervention."""

